### ISSUE TITLE
Objective of "shortest_path.py"

### ISSUE THREAD

**Issue by pksiwan11** [avinashu1980/Intro_Python_Gurobi#1]
I am able to run the code and it is giving correct results. But, I am unable to find the Objective function that is being minimized in the code. Is there any default Objective function in gurobipy for this?

Thanks in advance.

**Comment by avinashu1980** [comment]
> I am able to run the code and it is giving correct results. But, I am unable to find the Objective function that is being minimized in the code. Is there any default Objective function in gurobipy for this?
> 
> Thanks in advance.

Pankaj

The objective function cost is specified when the variables are defined
x = m.addVars(links, **obj=cost**, name ="flow")

**Comment by pksiwan11** [comment]
Can you please tell me, how to set objective explicitly via _model.setObjective()_  in this case?

Currently the objective is specified when variables are defined, but can it be done using _setObjective()_ ?

Thanks in advance.
